spring.application.name=Payment-Microservice

server.port=5003

spring.datasource.url=jdbc:mysql://mysql-25938aaa-liyanageisara-27f9.h.aivencloud.com:17376/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ei8qDaDCo1XG-5w5T6U
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Stripe Configuration
stripe.secret.key=
stripe.public.key=p


# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
